name: paper
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - scipy=1.12.0
  - matplotlib=3.8.2
  - pandas=2.2.2
  - pyyaml=6.0.1
  - pip
  - pip:
      - pytest==8.3.2
